name: chatbot
description: A new Flutter project to build a chatbot with LM Studio.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.0.15
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.15
  animated_text_kit: ^4.2.2
  sqflite: ^2.3.0
path: ^1.8.3 # nécessaire pour les chemins des DB


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Ajoutez cette ligne

flutter:
  uses-material-design: true
